version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Installing dependencies
      - mvn -B dependency:resolve
  build:
    commands:
      - echo Building the project
      - mvn -B package
artifacts:
  files:
    - target/*.jar  # Adjust if your output format differs, e.g., .war